// Adds a few demo novels with original placeholder text so you can see the layout.
// Usage: npm run seed        (delete them later from the admin panel)
const { db, tx } = require('../src/db');
const { setNovelGenres } = require('../src/queries');
const { textToHtml, wordCount } = require('../src/parse');

const genreId = (name) => db.prepare('SELECT id FROM genres WHERE name = ?').get(name)?.id;
const owner = db.prepare("SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1").get()?.id ?? null;

const SCENES = [
  'The morning bell rang across the valley, thin and silver, and the mist began to lift from the rice terraces one step at a time.',
  'Nobody in the village remembered who had planted the old ginkgo by the well, only that it had always been there, and that it did not like to be lied to.',
  '"You are late," said the innkeeper, without looking up from her ledger. "The road does not usually take this long, even for someone who walks as slowly as you."',
  'He set the lantern on the table. Its flame burned a steady blue, the colour of deep water, and gave off no heat at all.',
  'Somewhere beyond the ridge a caravan was singing, the words carried apart by the wind until only the rhythm remained.',
  '"Rules are simple," the old man said. "Take nothing you cannot carry. Promise nothing you cannot keep. And never answer the door after the third knock."',
  'The map had been redrawn so many times that the paper had gone soft as cloth, and three different hands had argued in the margins about where the river used to run.',
  'She counted her coins twice, then a third time, as if the number might change out of sympathy. It did not.',
  'Rain drummed on the tiled roof. Inside, the fire muttered to itself, and for a while nobody said anything worth remembering.',
  'At the edge of the market stood a stall that sold nothing but keys — hundreds of them, iron and brass and bone — and not one of them fit a lock in this city.',
  'The system window flickered into view, patient and polite, as though it had been waiting all night for him to wake up.',
  '[Quest updated: Find a place to sleep that is not a ditch.]',
  'The sword was too heavy, the armour too loose, and the dragon, frankly, looked bored.',
  'By the time the moon rose, the three of them had agreed on exactly one thing: nobody was going back the way they came.',
];

function makeChapter(seed, paragraphs = 14) {
  const out = [];
  for (let i = 0; i < paragraphs; i++) out.push(SCENES[(seed * 7 + i * 3) % SCENES.length]);
  out.splice(Math.floor(paragraphs / 2), 0, '***');
  return out.join('\n\n');
}

const NOVELS = [
  {
    title: 'The Lantern Keeper of Hollow Pass',
    alt: 'Hollow Pass Lantern\nLKHP',
    author: 'Demo Author', lang: 'Chinese', year: 2021, status: 'ongoing',
    genres: ['Fantasy', 'Adventure', 'Slice of Life'],
    tags: 'inn keeping, travel, slow life, found family',
    description: 'A quiet innkeeper at a mountain pass keeps a lantern that never goes out. Travellers come and go, each carrying a story they would rather not tell.\n\nThis is demo content generated by the seed script. Delete it from the admin panel whenever you like.',
    chapters: 24,
    titles: ['The Blue Flame', 'A Guest at Dusk', 'Ledger of Debts', 'The Third Knock', 'Market of Keys', 'Rain on the Roof'],
  },
  {
    title: 'Reincarnated as the Final Boss’s Accountant',
    alt: 'Final Boss Accountant',
    author: 'Another Demo', lang: 'Korean', year: 2023, status: 'ongoing',
    genres: ['Comedy', 'Isekai', 'System', 'Fantasy'],
    tags: 'system, comedy, overpowered paperwork, dungeon management',
    description: 'Dying of overwork was bad enough. Waking up in a demon lord’s fortress with a quest window demanding a balanced budget was worse.\n\nDemo content for layout testing.',
    chapters: 12,
    titles: ['Quarterly Report of Doom', 'The Dragon Is Over Budget', 'Minions Want Dental', 'Audit'],
  },
  {
    title: 'Sword Saint of the Nine Rivers',
    alt: '九河剑圣',
    author: 'Demo Writer', lang: 'Chinese', year: 2019, status: 'completed',
    genres: ['Wuxia', 'Martial Arts', 'Action'],
    tags: 'sword, sects, revenge, cultivation',
    description: 'A disgraced disciple walks the nine rivers to return a borrowed sword.\n\nDemo content for layout testing.',
    chapters: 8,
    titles: ['The Borrowed Blade', 'First River', 'Tea With an Enemy', 'The Ferryman'],
  },
];

tx(() => {
  NOVELS.forEach((n, ni) => {
    const slug = n.title.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
    if (db.prepare('SELECT 1 FROM novels WHERE slug = ?').get(slug)) return;
    const r = db.prepare(`INSERT INTO novels (slug, title, alt_titles, author, original_language, year, status, description, tags, owner_id, views, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, unixepoch() - ?, unixepoch() - ?)`)
      .run(slug, n.title, n.alt, n.author, n.lang, n.year, n.status, n.description, n.tags, owner, 500 + ni * 1700, 86400 * 30, ni * 3600);
    const id = Number(r.lastInsertRowid);
    setNovelGenres(id, n.genres.map(genreId).filter(Boolean));
    const ins = db.prepare('INSERT INTO chapters (novel_id, number, title, content, word_count, views, created_at) VALUES (?, ?, ?, ?, ?, ?, unixepoch() - ?)');
    for (let c = 1; c <= n.chapters; c++) {
      const html = textToHtml(makeChapter(c + ni));
      ins.run(id, c, n.titles[(c - 1) % n.titles.length], html, wordCount(html), Math.max(3, 200 - c * 7), (n.chapters - c) * 43200 + ni * 3600);
    }
    console.log(`Added “${n.title}” with ${n.chapters} chapters`);
  });
});
